//
//  SplitOutputNaming.swift
//  ZapPDF
//
//  Shared naming helpers for split output files.
//

import Foundation

/// Utilities for generating deterministic split output names.
enum SplitOutputNaming {

    /// Builds a compact page token from page numbers.
    ///
    /// Example: `[1, 2, 3, 5, 7, 8]` -> `"1-3_5_7-8"`
    static func pageToken(from pages: [Int]) -> String {
        let sortedPages = pages.sorted()
        guard let firstPage = sortedPages.first else {
            return "pages"
        }

        var tokens: [String] = []
        var runStart = firstPage
        var previous = firstPage

        for page in sortedPages.dropFirst() {
            if page == previous + 1 {
                previous = page
                continue
            }

            tokens.append(formatRange(start: runStart, end: previous))
            runStart = page
            previous = page
        }

        tokens.append(formatRange(start: runStart, end: previous))
        return tokens.joined(separator: "_")
    }

    /// Builds a split output file stem (without extension).
    ///
    /// - Parameters:
    ///   - baseName: Source filename without extension.
    ///   - pageToken: Token generated by `pageToken(from:)`.
    ///   - timestamp: Optional timestamp suffix (e.g. `250214_163355`).
    ///   - duplicateIndex: Optional duplicate index. Values > 1 append `_<n>`.
    static func makeStem(
        baseName: String,
        pageToken: String,
        timestamp: String?,
        duplicateIndex: Int?
    ) -> String {
        var stem = "\(baseName)_p\(pageToken)"

        if let timestamp, !timestamp.isEmpty {
            stem += "_\(timestamp)"
        }

        if let duplicateIndex, duplicateIndex > 1 {
            stem += "_\(duplicateIndex)"
        }

        return stem
    }

    private static func formatRange(start: Int, end: Int) -> String {
        if start == end {
            return "\(start)"
        }
        return "\(start)-\(end)"
    }
}
